language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
before_script:
  - npm install -g bower
  - npm install -g gulp
  - npm install -g gulp-jasmine
  - bower install
  - gulp test
  - gulp lint